bffbook/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import private_chats
from .views import home_view, logout, login
from chats.views import public_chats_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home_view'),
    path('profiles/', include('profiles.urls',  namespace='profiles')),
    path('accounts/', include('allauth.urls')),
    path('login', login, name='login'),
    path('logout', logout, name='logout'),
    path('chats/', public_chats_view, name='chats'),
    path('private_chats/', include('private_chats.urls', namespace='private_chats')),
    # path('posts/', include('posts.urls',  namespace='posts'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chats/urls.py
# from django.urls import path
# from .views import public_chats_view
# app_name = 'chats'
#
# urlpatterns = [
#     path('public_chats/', public_chats_view, name='public_chats')
# ]

private_chats/urls.py
from django.urls import path
from private_chats.views import private_chat_room_view, create_or_return_private_chat

app_name = "private_chats"

urlpatterns = [
    path("", private_chat_room_view, name="private-chat-room"),
    path("create_or_return_private_chat/", create_or_return_private_chat,
         name="create-or-return-private-chat"),
]

profiles/urls.py
from django.urls import path
from .views import (like_unlike_post,
                    delete_update_comment, delete_update_post,
                    invites_received_view,
                    ProfileListView, ProfileDetailView,
                    send_invitation, remove_friend,
                    accept_reject_invitation
                    )

app_name = 'profiles'

urlpatterns = [
    path('liked/', like_unlike_post, name='like-post-view'),
    path('delete-update-comment/', delete_update_comment, name='delete-update-comment'),
    path('delete-update-post/', delete_update_post, name='delete-update-post'),
    path('friends/', invites_received_view, name='friends'),
    path('all-profiles/', ProfileListView.as_view(), name='all-profiles-view'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('send-invite', send_invitation, name='send-invite'),
    path('remove-friend', remove_friend, name='remove-friend'),
    path('accept-reject-invitation', accept_reject_invitation, name='accept-reject-invitation'),
]

templates/main/home.html
{% extends 'base.html' %}

{% block title %}
home
{% endblock title %}

{% block content %}
{% if not request.user.is_authenticated %}
    <meta http-equiv="refresh" content="0; url=/accounts/login/"/>
{% else %}
    <meta http-equiv="refresh" content="0; url={% url 'profiles:profile-detail-view' slug=request.user.profile.slug %}"/>
{% endif %}
{% endblock content %}

{% block scripts %}
<script>

</script>
{% endblock scripts %}

templates/main/login.html
{% extends 'base.html' %}

{% block title %}
home
{% endblock title %}

{% block content %}
<form class="ui form" action="{% url 'login' %}" method="POST">
    {% csrf_token %}
  <div class="field">
    <label>Username</label>
    <input type="text" name="username" placeholder="username" required>
  </div>
  <div class="field">
    <label>Password</label>
    <input type="text" name="password" placeholder="password" required>
  </div>
  <div class="field">
    <div class="ui checkbox">
      <input type="checkbox" tabindex="0" class="hidden">
      <label>I agree to the Terms and Conditions</label>
    </div>
  </div>
  <button type="submit" value="Login" class="ui button">Submit</button>
</form>
{% endblock content %}

{% block scripts %}
<script>

</script>
{% endblock scripts %}

templates/main/navbar.html
<!--{% url 'home_view' as path_to_home %}-->
<!--{% url 'posts:main-post-view' as path_to_posts %}-->
<!--{% url 'profiles:my-profile-view' as path_to_my_profile %}-->
<!--{% url 'profiles:my-invites-view' as path_to_my_invites %}-->
<!--{% url 'profiles:friends' as friends %}-->
<!--{% url 'chats' as chats %}-->
<!--{% url 'private_chats:private-chat-room' as private_chats %}-->
<!--{% url 'profiles:all-profiles-view' as all_profiles %}-->
<!--{% url 'profiles:profile-detail-view' slug=request.user.profile.slug as my_profile %}-->
<div class="ui inverted menu nav mb-7">
  <div class="ui container">
    <a href="{{path_to_home}}" class="{% if request.path == path_to_home %}active{% endif %} item">
        <h3>InTouch</h3>
    </a>
    {% if request.user.is_authenticated %}
    <a href="{{ my_profile }}" class="{% if request.path == my_profile %}active{% endif %} item">
        My profile
        <img src="{{ avatar.url }}" class="nav-avatar">
    </a>
    <a href="{{friends}}" class="{% if request.path == friends %}active{% endif %} item">
        Friends
    </a>
    <a href="{{chats}}" class="{% if request.path == chats %}active{% endif %} item">
        Public chat
    </a>
    <a href="{{private_chats}}" class="{% if request.path == private_chats %}active{% endif %} item">
        My chats
    </a>
    <a href="{{all_profiles}}" class="{% if request.path == all_profiles %}active{% endif %} item">
        All profiles
    </a>

    {% endif %}

    <div class="right menu">
        {% if request.user.is_authenticated %}

             <div class="item">
                <form action="" method="GET">
                    <div class="ui action left icon input">
                    <input class="prompt" type="text" name='q' placeholder="name of a friend...">
                    <i class="search icon"></i>
                    <button type='submit' class="ui button">Search</button>
                    </div>
                </form>
            </div>

             <div class="ui dropdown notifications">
              <i class="bell icon notification-icon container_icon">
                  <div class="" id="notifications_indicator"></div>
              </i>
              <span id="notifications_page_number" style="display: none;">1</span>
              <div class="menu notification-menu transition hidden">
                <div class="ui divided items" id="notification-container">
{#                  <div class="item">#}
{#                    <div class="ui tiny image">#}
{#                      <img src="/media/avatars/6066341416.jpg">#}
{#                    </div>#}
{#                      <div class="author" >#}
{#                          <a href="test">Aleksandr Kiselev</a><time>Five minutes ago</time>#}
{#                      </div>#}
{#                      <br>#}
{#                    <div class="content">#}
{#                        <p>Text</p>#}
{#                    </div>#}
{#                  </div>#}
                </div>
              </div>
            </div>

            <a class="ui item" href="{% url 'account_logout' %}">
                <i class="sign out alternate icon"></i>Logout
            </a>

        {% endif %}
    </div>
  </div>
</div>