bffbook/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import private_chats
from .views import home_view, logout, login
from chats.views import public_chats_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home_view'),
    path('profiles/', include('profiles.urls',  namespace='profiles')),
    path('accounts/', include('allauth.urls')),
    path('login', login, name='login'),
    path('logout', logout, name='logout'),
    path('chats/', public_chats_view, name='chats'),
    path('private_chats/', include('private_chats.urls', namespace='private_chats')),
    # path('posts/', include('posts.urls',  namespace='posts'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chats/urls.py
# from django.urls import path
# from .views import public_chats_view
# app_name = 'chats'
#
# urlpatterns = [
#     path('public_chats/', public_chats_view, name='public_chats')
# ]

private_chats/urls.py
from django.urls import path
from private_chats.views import private_chat_room_view, create_or_return_private_chat

app_name = "private_chats"

urlpatterns = [
    path("", private_chat_room_view, name="private-chat-room"),
    path("create_or_return_private_chat/", create_or_return_private_chat,
         name="create-or-return-private-chat"),
]

templates/snippets/create_or_return_private_chat.html
<script type="text/javascript">
  function createOrReturnPrivateChat(id){
          let payload = {
              "csrfmiddlewaretoken": "{{csrf_token}}",
              "user2_id": id,
          }
          $.ajax({
              type: "POST",
              dataType: "json",
              url: "{% url 'private_chats:create-or-return-private-chat' %}",
              data: payload,
              timeout: 5000,
              success: function (data){
                  console.log('SUCCESS', data)
                  if (data.response === 'Successfully got the chat'){
                      let chatroomId = data.chatroom_id
                      onGetOrCreateChatRoom(chatroomId)
                  }
                  else if(data.response != null) {
                      alert(data.response)
                  }
              },
              error: function (data){
                  console.log('ERROR AJAX' + data)
              },
              complete: function (data){
                  // nothing
              },
          })
      } // end of createOrReturnPrivateChat

  function onGetOrCreateChatRoom(chatroomId){
      let url = "{% url 'private_chats:private-chat-room' %}?room_id=" + chatroomId;
      let win = window.location.replace(url)
      win.focus()
  }

</script>