bffbook/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import private_chats
from .views import home_view, logout, login
from chats.views import public_chats_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home_view'),
    path('profiles/', include('profiles.urls',  namespace='profiles')),
    path('accounts/', include('allauth.urls')),
    path('login', login, name='login'),
    path('logout', logout, name='logout'),
    path('chats/', public_chats_view, name='chats'),
    path('private_chats/', include('private_chats.urls', namespace='private_chats')),
    # path('posts/', include('posts.urls',  namespace='posts'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chats/urls.py
# from django.urls import path
# from .views import public_chats_view
# app_name = 'chats'
#
# urlpatterns = [
#     path('public_chats/', public_chats_view, name='public_chats')
# ]

profiles/urls.py
from django.urls import path
from .views import (like_unlike_post,
                    delete_update_comment, delete_update_post,
                    invites_received_view,
                    ProfileListView, ProfileDetailView,
                    send_invitation, remove_friend,
                    accept_reject_invitation
                    )

app_name = 'profiles'

urlpatterns = [
    path('liked/', like_unlike_post, name='like-post-view'),
    path('delete-update-comment/', delete_update_comment, name='delete-update-comment'),
    path('delete-update-post/', delete_update_post, name='delete-update-post'),
    path('friends/', invites_received_view, name='friends'),
    path('all-profiles/', ProfileListView.as_view(), name='all-profiles-view'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('send-invite', send_invitation, name='send-invite'),
    path('remove-friend', remove_friend, name='remove-friend'),
    path('accept-reject-invitation', accept_reject_invitation, name='accept-reject-invitation'),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import get_random_code
from django.template.defaultfilters import slugify
from django.db.models import Q


class ProfileManager(models.Manager):

    def get_all_profiles_to_invite(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        qs = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))

        accepted = []
        for rel in qs:
            if rel.status == 'accepted':
                accepted.append(rel.receiver)
                accepted.append(rel.sender)

        available = [profile for profile in profiles if profile not in accepted]
        return available

    def get_all_profiles(self, me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles


class Profile(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default="no bio...", max_length=600)
    email = models.EmailField(max_length=200, blank=True)
    country = models.CharField(max_length=200, blank=True)
    avatar = models.ImageField(default='avatar.png', upload_to='avatars/')
    friends = models.ManyToManyField(User, blank=True, related_name='friends')
    slug = models.SlugField(unique=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = ProfileManager()

    def get_friends(self):
        return self.friends.all()

    def get_friends_no(self):
        return self.friends.all().count()

    def get_posts_no(self):
        return self.posts.all().count()

    def get_all_authors_posts(self):
        # здесь обращаемся по related_name
        return self.posts.all()

    def get_likes_given_no(self):
        likes = self.like_set.all()
        total_liked = 0
        for item in likes:
            if item.value == 'Like':
                total_liked += 1
        return total_liked

    def get_likes_recieved_no(self):
        posts = self.posts.all()
        total_liked = 0
        for item in posts:
            total_liked += item.liked.all().count()
        return total_liked

    def __str__(self):
        return f"{self.user.username}--{self.created.strftime('%d-%m-%Y')}"

    def save(self, *args, **kwargs):
        ex = False
        if self.first_name and self.last_name and not self.slug:
            to_slug = slugify(str(self.first_name + " " + self.last_name))
            ex = Profile.objects.filter(slug=to_slug).exists()
            while ex:
                to_slug = slugify(to_slug + " " + str(get_random_code()))
                ex = Profile.objects.filter(slug=to_slug).exists()
            self.slug = to_slug
        elif self.slug:
            pass
        else:
            to_slug = str(self.user)
            self.slug = to_slug
        super().save(*args, **kwargs)


STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted')
)


class RelationshipManager(models.Manager):
    def invitations_received(self, receiver):
        qs = Relationship.objects.filter(receiver=receiver, status='send')
        return qs


class Relationship(models.Model):
    sender = models.ForeignKey(Profile,
                               on_delete=models.CASCADE,
                               related_name='sender')
    receiver = models.ForeignKey(Profile,
                                 on_delete=models.CASCADE,
                                 related_name='reciever')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = RelationshipManager()

    def __str__(self):
        return f"{self.sender}--{self.receiver}--{self.status}"

    @property
    def get_cname(self):
        return "FriendRequest"

profiles/forms.py
from django import forms
from .models import Profile
from posts.models import Post, Comment


class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'bio', 'avatar')


class PostModelForm(forms.ModelForm):
    content = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 2, 'class': 'field'}))
    class Meta:
        model = Post
        fields = ('content', 'image')


class CommentModelForm(forms.ModelForm):
    label = ""
    body = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Add a comment', 'label': 'Comment'},), label="")

    class Meta:
        model = Comment
        fields = ('body',)

profiles/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from .models import Profile, Relationship
from posts.models import Post, Like, Comment
from .forms import ProfileModelForm, PostModelForm, CommentModelForm
from django.views.generic import UpdateView, DeleteView, ListView, DetailView
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from notifications.models import Notifications, Clients
from django.contrib.contenttypes.models import ContentType
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
OBJ_ID_FRIENDS_REQUESTS = 1
OBJ_ID_NEW_LIKE = 2


@login_required
def like_unlike_post(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Post.objects.get(id=post_id)
        profile = Profile.objects.get(user=user)

        if profile in post_obj.liked.all():
            post_obj.liked.remove(profile)
        else:
            post_obj.liked.add(profile)

        like, created = Like.objects.get_or_create(user=profile, post_id=post_id)

        if not created:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'
                create_like_notification(like, post_obj,  user, 'new like', OBJ_ID_NEW_LIKE)
        else:
            like.value = 'Like'
            create_like_notification(like, post_obj, user, 'new like', OBJ_ID_NEW_LIKE)
        post_obj.save()
        like.save()

    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def delete_update_post(request):
    user = request.user
    post_id = request.POST.get('post_id')
    post = Post.objects.get(id=post_id)
    if 'delete_post' in request.POST:
        if not post.author.user == user:
            messages.warning(request,
                             'You need to be the author of the comment')
        else:
            post.delete()
    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def delete_update_comment(request):
    user = request.user
    comment_id = request.POST.get('comment_id')
    comment = Comment.objects.get(id=comment_id)
    post_id = request.POST.get('post_id')
    if 'delete_comment' in request.POST:
        if not comment.user.user == user:
            messages.warning(request,
                             'You need to be the author of the comment')
        else:
            comment.delete()
    if 'update_comment' in request.POST:

        if not comment.user.user == user:
            messages.warning(request,
                             'You need to be the author of the comment')
        else:
            comment.body = request.POST.get("comment_body")
            comment.save()
    return redirect(request.META.get('HTTP_REFERER') + '#post-' + post_id)


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'posts/confirm_del.html'
    success_url = reverse_lazy('profiles:my-profile-view')

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        post = Post.objects.get(pk=pk)
        if not post.author.user == self.request.user:
            messages.warning(self.request,
                             'You need to be the author of the post')
        return post


class PostUpdateView(LoginRequiredMixin, UpdateView):
    form_class = PostModelForm
    template_name = 'posts/update.html'
    success_url = reverse_lazy('profiles:my-profile-view')

    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        if form.instance.author == profile:
            return super().form_valid(form)
        else:
            form.add_error(None, "You need to be the author of the post")
            return super().form_invalid(form)


@login_required
def invites_received_view(request):
    profile = Profile.objects.get(user=request.user)
    friend_requests = Relationship.objects.invitations_received(profile)

    context = {'friend_requests': friend_requests}

    return render(request, 'profiles/friends.html', context)


@login_required
def accept_reject_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)

        if rel.status == 'send':
            content_type = ContentType.objects.get_for_model(Relationship)
            if 'approve_request' in request.POST:
                rel.status = 'accepted'
                rel.save()

                # create notification
                Notifications(target=sender.user,
                              from_user=receiver.user,
                              redirect_url=f"/profiles/{receiver.slug}/",
                              verb=f"Your friend request to user {receiver.first_name} {receiver.last_name} accepted",
                              content_type=content_type,
                              object_id=OBJ_ID_FRIENDS_REQUESTS,
                              ).save()
            elif 'decline_request' in request.POST:
                rel.delete()

                # create notification
                Notifications(target=sender.user,
                              from_user=receiver.user,
                              redirect_url=f"/profiles/{receiver.slug}/",
                              verb=f"Your friend request to user {receiver.first_name} {receiver.last_name} rejected",
                              content_type=content_type,
                              object_id=OBJ_ID_FRIENDS_REQUESTS,
                              ).save()

        return redirect(request.META.get('HTTP_REFERER'))


@login_required
def profiles_list_view(request):
    user = request.user
    qs = Profile.objects.get_all_profiles(user)

    context = {'qs': qs}

    return render(request, 'profiles/profiles_list.html', context)


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'profiles/user_profile.html'
    context_object_name = 'profile'

    def get_object(self):
        slug = self.kwargs.get('slug')
        print('*'*100)
        print(slug)
        profile = Profile.objects.get(slug=slug)
        return profile

    def post(self, request, *args, **kwargs):
        user = request.user
        if 'submit_profile' in request.POST:
            profile_form = ProfileModelForm(request.POST or None,
                                            request.FILES or None,
                                            instance=Profile.objects.get(user=user))
            # profile form
            if profile_form.is_valid():
                profile_form.save()

        if 'submit_post' in request.POST:
            post_form = PostModelForm(request.POST, request.FILES)
            page_id = request.POST.get('page_id')
            if post_form.is_valid():
                instance = post_form.save(commit=False)
                instance.author = Profile.objects.filter(user=request.user).get()
                instance.page_id = page_id
                instance.save()

        elif 'submit_comment' in request.POST:
            comment_form = CommentModelForm(request.POST)
            if comment_form.is_valid():
                instance = comment_form.save(commit=False)
                instance.user = Profile.objects.filter(user=request.user).get()
                instance.post = Post.objects.get(id=request.POST.get('post_id'))
                instance.save()
                comment_form = CommentModelForm()

        elif 'delete_comment' in request.POST:
            comment_id = request.POST.get('comment_id')
            comment = Comment.objects.get(id=comment_id)
            if not comment.user.user == user:
                messages.warning(request,
                                 'You need to be the author of the comment')
            else:
                comment.delete()
        elif 'update_comment' in request.POST:
            comment_id = request.POST.get('comment_id')
            comment = Comment.objects.get(id=comment_id)
            if not comment.user.user == user:
                messages.warning(request,
                                 'You need to be the author of the comment')
            else:
                comment.body = request.POST.get("comment_body")
                comment.save()
        return redirect(request.META.get('HTTP_REFERER'))

    def get_context_data(self, **kwargs):
        # передает значения в context
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        user_profile = self.get_object()
        context['posts'] = Post.objects.filter(page_id=user_profile.id)
        context['post_form'] = PostModelForm()
        context['comment_form'] = CommentModelForm()
        context['post_added'] = False
        print(profile, user_profile)
        if profile == user_profile:
            context['profile_form'] = ProfileModelForm(instance=profile)

        return context


class ProfileListView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = 'profiles/profiles_list.html'
    context_object_name = 'qs'

    def get_queryset(self):

templates/profiles/myprofile.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% block title %}
My Profile
{% endblock %}

{% block content %}
<!-- Modal -->
<div class="ui modal profile my-modal">
  <i class="close icon"></i>
  <div class="header">
    Update your profile
  </div>
  <div class="image content">
    <div class="ui medium image">
      <img src="{{ profile.avatar.url }}">
    </div>
    <div class="description">
      <div class="ui header">Change your info here</div>
        <form id="update_profile" name="submit_profile" action="" method="POST" class="ui form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
        </form>
    </div>
  </div>
  <div class="actions">
    <button form="update_profile" name="submit_profile" type="submit"
            class="ui positive right labeled icon button">
      Update
      <i class="checkmark icon"></i>
    </button>

  </div>
</div>

<!--Alert-Message -->
{% if confirm %}
    <div class="ui message positive">
        <i class="close icon"></i>
        <div class="header">
            Updated
        </div>
    </div>
{% endif %}
<div class="ui segment">
    <!-- Profile info -->
    <h3>{{ profile.first_name }} {{ profile.last_name }}</h3>
    <hr>
    <div class="ui grid">
        <div class="row ui center aligned">
            <div class="six wide column">
                <img class="avatar ui small rounded image" src="{{ profile.avatar.url }}"/>
                <br/>
                <button class="ui secondary button" id="modal-btn-edit-profile">Edit profile</button>
            </div>
            <div class="ten wide column">
                <table class="ui table">
                    <tbody>
                        <tr>
                            <td>Birthdate</td>
                            <td>12.03.1997</td>
                        </tr>
                        <tr>
                            <td>Country</td>
                            <td>{{ profile.country }}</td>
                        </tr>
                        <tr>
                            <td>City</td>
                            <td>Moscow</td>
                        </tr>
                        <tr>
                            <td>Bio</td>
                            <td>{{ profile.bio }}</td>
                        </tr>
                        <tr>
                            <td>All posts num</td>
                            <td>{{ profile.get_posts_no }}</td>
                        </tr>
                        <tr>
                            <td>All given likes</td>
                            <td>{{ profile.get_likes_given_no }}</td>
                        </tr>
                        <tr>
                            <td>All recieved likes</td>
                            <td>{{ profile.get_likes_recieved_no }}</td>
                        </tr>
                    </tbody>
                </table>
                <p></p>
            </div>

        </div>
        <!-- Friends list -->
        <div class="row ui center aligned">
            <div class="six wide column">
                <div class="friends">
                    <h2>Friends ({{ profile.get_friends_no }})</h2>
                    {% for friend in profile.get_friends %}
                        <div class="friend" >
                            <p> {{ friend }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        <!-- Friends list end -->

        <!-- Posts start -->
            <div class="ten wide column">
                <h2>My Posts </h2>
                {% if post_added %}
                    <div class="ui message positive">
                        <i class="close icon"></i>
                        <div class="header">
                            New post was successfully added
                        </div>
                    </div>
                {% endif %}
                <div class="ui segment raised create-post-form">
                    <form action="" method="POST" class="ui form" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="page_id" value="{{ profile.user.id }}">
                        {{ post_form }}
                        <button type="submit" name="submit_post" class="ui button positive">
                            Send post
                        </button>
                    </form>
                </div>
                {% for post in posts %}
                <div class="ui segment raised profile-posts">
                    <a name="post-{{ post.id }}" style="display: none;"></a>
                    <div class="post-header">
                        {% if request.user == post.author.user or request.user.id == post.page_id  %}
                            <form action="{% url 'profiles:delete-update-post' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="post_id" value="{{ post.id }}">
                                <button name="delete_post" title="Delete post" type="submit"  class="delete-post-button"><i class="close icon"></i></button>
                              </form>
                        {% endif %}
                        <img class="post-avatar image" src="{{ post.author.avatar.url }}"/>
                        <p class="post-author">{{ post.author.first_name }} {{ post.author.last_name }}</p>
                        <p class="post-time">{{ post.created | naturalday }}</p>
                    </div>
                    <p class="post-text">{{ post.content }}</p>
                    <p class="post-img">
                        {% if post.image %}
                            <img class="post-img" src="{{ post.image.url }}" alt="">
                        {% endif %}
<!--                        <img class="post-img" src="https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg" alt="">-->
                    </p>
                    <!-- Start post-actions -->
                    <div class="post-actions">
                        <div class="ui tiny labeled button" tabindex="0">
                            <form action="{% url 'profiles:like-post-view' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="post_id" value="{{ post.id }}">

                                        {% if profile in post.liked.all %}
                                            <button type="submit"
                                                    class="ui tiny black button like-button-counter">
                                                <i class="heart icon"></i> Unlike
                                            </button>
                            </form>
                                            <a class="ui basic black left  label"
                                               data-tooltip="List of users who liked your post"
                                               data-inverted="">
                                                    {{ post.num_likes }}
                                            </a>
                                        {% else %}
                                            <button type="submit"
                                                    class="ui tiny  red button like-button-counter">
                                                <i class="heart icon"></i> Like
                                            </button>
                                            </form>
                                            <a class="ui basic red left  label"
                                               data-tooltip="List of users who liked your post"
                                               data-inverted="">
                                                    {{ post.num_likes }}
                                            </a>
                                        {% endif %}

                        </div>
                        <a class="post-add-comment"><i class="pencil alternate icon"></i>Add comment</a>
                    </div>
                    <!-- End post-actions -->
                    <!-- Start comments -->
                    <div class="ui comments">
                      <h3 class="ui dividing header">Comments</h3>
                        {% for comment in post.comment_set.all %}
                          <div class="comment">
                              {% if request.user == comment.user.user or request.user == comment.user %}
                             <!-- Modal delete comment start -->
                              <form action="{% url 'profiles:delete-update-comment' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="post_id" value="{{ post.id }}">
                                <input type="hidden" name="comment_id" value="{{ comment.id }}">
                                <button name="delete_comment" title="Delete comment" type="submit"  class="delete-comment-button"><i class="close icon"></i></button>
                              </form>
                              {% endif %}
                              <!-- Modal delete comment end -->
                              <!-- Modal update comment start -->
                              {% if request.user == comment.user.user %}
                                <div class="ui modal update-comment-{{ comment.id }} my-modal">
                                  <i class="close icon"></i>
                                  <div class="header">
                                    Update comment
                                  </div>
                                  <div class="image content">
                                    <div class="description">
                                      <div class="ui header">Change your comment here</div>
                                        <form id="update_comment-{{ comment.id }}" name="update_comment" action="{% url 'profiles:delete-update-comment' %}"
                                              method="POST" class="ui form">
                                            {% csrf_token %}
                                            <input type="hidden" name="comment_id" value="{{ comment.id }}">
                                            <input type="hidden" name="post_id" value="{{ post.id }}">
                                            <input type="text" name="comment_body" value="{{ comment.body }}">
                                        </form>
                                    </div>
                                  </div>
                                  <div class="actions">
                                    <button form="update_comment-{{ comment.id }}" name="update_comment" type="submit"
                                            class="ui positive right labeled icon button">
                                      Update
                                      <i class="checkmark icon"></i>
                                    </button>

                                  </div>
                                </div>
                                <button title="Edit comment" onclick="$('.ui.modal.update-comment-{{ comment.id }}') .modal('show');" class="update-comment-button"><i class="edit icon"></i></button>
                              {% endif %}
                            <a class="avatar-comments">
                              <img src="{{ comment.user.avatar.url }}">
                            </a>
                            <div class="content">
                              <a class="author">
                                  {{ comment.user.first_name }} {{ comment.user.last_name }}
                              </a>
                              <div class="metadata">
                                <span class="date">{{ comment.created | naturalday }}</span>
                              </div>
                              <div class="text">
                                <p>{{ comment.body }}</p>
                                <div class="actions">
                                    <a class="reply">Reply</a>
                                </div>
                              </div>
                            </div>
                          </div>
                        {% endfor %}
                      <form action="#post-{{ post.id }}" method="POST" class="ui reply form comments-form">
                        {% csrf_token %}
                        {{ comment_form }}
                        <input type="hidden" name="post_id" value="{{ post.id }}">
                        <button type="submit" name="submit_comment"
                                class="ui mini blue labeled submit icon button comment-submit-button">
                          <i class="icon edit"></i> Add Reply
                        </button>
                      </form>
                    <!-- End comments -->

                </div>
            </div>        
            {% endfor %}
            <!-- Posts end -->


        </div>
    </div>
    <hr>

</div>

{% endblock %}